### ISSUE TITLE
Formatting Error: <BR> shows up everywhere when viewing unit stats.

### ISSUE THREAD

**Issue by Tammo-Korsai** [BSData/wh40k-epic-armageddon#20]
Breaks show up as <BR> as shown in the screenshot below. I loaded up a 40k roster as well to see if it was a wider issue, but this formatting error shows only for Epic Armageddon. 

![Clipboard01](https://user-images.githubusercontent.com/49999868/113603278-aa570a80-963b-11eb-980e-913f823b740f.png)

**Comment by afraeve** [comment]
The <BR> tag used to make a line break, so the example you're looking would appear neatly as:

Bolters                  (15cm)   Small Arms

Missile Launcher   45cm     AP5+/AT6+

It was really useful for the more complicated profiles. Sadly, the BattleScribe developer removed that functionality when 40k 8th ed was released, probably because of the new "keywords" in that game that use the <> symbols.
He might include some other markup text in future that I can replace them with, but until then, there's nothing I can do.
